### ISSUE TITLE
ncsdk2.5 install error 

### ISSUE THREAD

**Issue by tuqingyun** [PINTO0309/MobileNet-SSD#2]
when i run make install i meet the error of Installation failed: Command 'sudo -H -E pip3 install  --trusted-host files.pythonhosted.org Cython graphviz scikit-image' return code=2. Error on line 308 in ./install-utilities.sh.  Will exit   
i want to know how to solve it

**Comment by PINTO0309** [comment]
@tuqingyun

1.RaspberryPi + Raspbian Stretch?
2.There was a mistake in the contents of the README, so I corrected it.
What if I try again with the following command sequence?
```
$ cd ~
$ rm -r -f ncsdk
$ git clone -b ncsdk2 https://github.com/movidius/ncsdk.git
$ cd ncsdk
$ make install
```

**Comment by tuqingyun** [comment]
yes but the os is 32bit
i use the ncskd2 meet the msitake

**Comment by PINTO0309** [comment]
@tuqingyun
Please open the terminal and tell the full sentence the result of directly executing the following.
```
$ sudo -H -E pip3 install --trusted-host files.pythonhosted.org Cython graphviz scikit-image
```

**Comment by tuqingyun** [comment]
ok thank you 
please wait a minute i run make install again

**Comment by tuqingyun** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python3/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/lib/python3/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/lib/python3/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/lib/python3/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/lib/python3/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 303, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
Installation failed: Command 'sudo -H -E pip3 install  --trusted-host files.pythonhosted.org Cython graphviz scikit-image' return code=2. Error on line 308 in ./install-utilities.sh.  Will exit
Makefile:47: recipe for target 'install' failed
make: *** [install] Error 131

**Comment by tuqingyun** [comment]
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 298, in _error_catcher
    yield
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

**Comment by PINTO0309** [comment]
@tuqingyun
The pip communication seems to be blocked in the network.
If you are working within the company, please show this log to the network representative and have the 443 port communication permitted.
Now, I also ran the same command via the mobile router, but it completes without problems.
![aaa](https://user-images.githubusercontent.com/33194443/43386606-2284eab2-941f-11e8-8412-723da5bb2cd8.png)

**Comment by tuqingyun** [comment]
OK  I'll try it.

**Comment by tuqingyun** [comment]
I also have another question about this project. The time I used to perform a NCS in version 1 was 150ms, but I saw that you were actually running at a time of only more than 80 ms, because of the reason for version 2？

**Comment by PINTO0309** [comment]
@tuqingyun 
Do you have a V1 program that you tried on this repository?
If it is not, I think that it is a problem of program performance.
I remember that there was no clear difference between V1 and V2.
It may be misunderstanding. . .

Multithread and MultiProcessing operate fast.
RaspberryPi is very weak on screen rendering.
This program executes screen rendering and prediction asynchronously and improves efficiency.

**Comment by tuqingyun** [comment]
OK I understand
The network I share with my cell phone still can not be installed successfully. How do I need to operate it to let the 443 port communication permitted.

**Comment by PINTO0309** [comment]
@tuqingyun 
Ummmm...
Because the communication system is different depending on the country, it can not be instructed precisely...
For example, China often hears that communication is restricted.

**Comment by tuqingyun** [comment]
thanks very much I'll try another methods

**Comment by PINTO0309** [comment]
@tuqingyun 
I will close this "issue" once.
Please open another "issue" again if there is progress.
